services:
  - type: web
    name: hms-backend
    env: python
    plan: starter
    buildCommand: "./build.sh"
    startCommand: "gunicorn hms_backend.wsgi:application"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: RENDER
        value: true
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: hms-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: hms-redis
          property: connectionString

databases:
  - name: hms-postgres
    plan: starter

services:
  - type: redis
    name: hms-redis
    plan: starter